name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Repo checkout
    - name: Checkout Code
      uses: actions/checkout@v2

    # SonarLint taraması
    - name: Run SonarLint
      run: |
        echo "SonarLint taraması gerçekleştiriliyor..."
        sonar-scanner -Dsonar.projectKey=my_project_key \
                       -Dsonar.sources=. \
                       -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                       -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # Docker için login
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Docker build ve push işlemi
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/flask-api:${{ github.sha }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
